### PR TITLE
resize and decrease quality in new camera

### PR DESCRIPTION
**Pull request by vdranik**

### CODE REVIEW

**Comment by dima-ko** [comment]
why do we need to decrease quality?

**Comment by vdranik** [comment]
why not?
than less the quality, the smaller the size of
we can change the picture quality

**Comment by dima-ko** [comment]
@excieve do you think we should decrease quality?

**Comment by exipilis** [comment]
Lets make some live tests of compression with quality 75-90.

2016-10-31 16:19 GMT+02:00 insomnaicJustin notifications@github.com:

**Comment by excieve** [comment]
I agree we need it. For my phone, each photo is about 2.5MB in 4K resolution, which is too much really. @exipilis mentioned we should resize to something around 1024x1024 I think. But it might screw the aspect ratio so might need to be a bit smarter.

**Comment by exipilis** [comment]
@excieve  just proportional resize to fit in 1024x1024 and throw all exif data to decrease file size.

**Comment by excieve** [comment]
Ah, it was about quality, not resizing. Agree with @exipilis let's test and see what's acceptable. Ideally the less resulting size of the files the better.

**Comment by dima-ko** [comment]
ok, but I'd rather keep exif data, just in case. it has timestamp, etc..

**Pull request merged**
